all:
  hosts:
    hopper:
      ansible_host: hopper.box.pydis.wtf
      ip: 89.58.24.117
      access_ip: 89.58.24.117
    turing:
      ansible_host: turing.box.pydis.wtf
      ip: 89.58.25.151
      access_ip: 89.58.25.151
    lovelace:
      ansible_host: lovelace.box.pydis.wtf
      ip: 89.58.26.118
      access_ip: 89.58.26.118
    neumann:
      ansible_host: neumann.box.pydis.wtf
      ip: 89.58.12.244
      access_ip: 89.58.12.244
    ritchie:
      ansible_host: ritchie.box.pydis.wtf
      ip: 89.58.25.224
      access_ip: 89.58.25.224
  children:
    kube_control_plane:
      hosts:
        hopper:
        turing:
    kube_node:
      hosts:
        hopper:
        turing:
        lovelace:
        neumann:
        ritchie:
    etcd:
      hosts:
        hopper:
        turing:
        lovelace:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
